channels:
- conda-forge
dependencies:
  - python=3.8
  - pip=20.0.2
  - pip:
    - lightgbm~=3.2.1
    - pandas~=1.3.5
    - scikit-learn~=1.0.2
    - typer~=0.4.0
    - pyarrow~=6.0.1
    - matplotlib~=3.5.0
    - mlflow
    - azureml-mlflow==1.38.0
name: nyc-taxi